<?php

namespace App\Http\Controllers;

use App\Models\NotificationDelivery;
use App\Models\NotificationSubscription;
use App\Services\Notifications\NotificationCatalogue;
use Illuminate\Http\Request;

/**
 * Handles RFC 8058 one-click unsubscribe.
 *
 * Reached by mail clients without a session, which is why the URL is signed rather than
 * authenticated. The signature is the authorisation: it proves the link was generated by
 * us for this delivery, and it cannot be edited to unsubscribe an arbitrary address.
 *
 * Unsubscribing is scoped to the delivery's category, never the whole address. Someone
 * who mutes monthly reports must still receive their billing notices, and an opt-out
 * that silenced everything would be the same complaint in reverse.
 */
class UnsubscribeNotificationController extends Controller
{
    public function __invoke(
        Request $request,
        NotificationDelivery $delivery,
        NotificationCatalogue $catalogue,
    ) {
        // A mandatory notification is not suppressible, so there is nothing valid to do
        // here. Answered explicitly rather than ignored: reaching this means a
        // transactional mail was sent with an unsubscribe header, which is the bug the
        // header tests in NotificationMailTest guard against.
        if ($delivery->is_mandatory) {
            return response()->json([
                'message' => 'This message is transactional and cannot be unsubscribed.',
            ], 422);
        }

        $address = $delivery->recipient_address;

        if (blank($address)) {
            return response()->json(['message' => 'Nothing to unsubscribe.'], 422);
        }

        $subscription = NotificationSubscription::forEmail($address);

        // An empty categories column means "everything allowed", so the first opt-out
        // has to be materialised as an explicit list before one item can be removed
        // from it. Storing the removal against an empty column would be a no-op.
        $current = $subscription->categories ?: $catalogue->optionalCategories();

        $remaining = array_values(array_diff($current, [$delivery->category]));

        $subscription->forceFill([
            'categories' => $remaining,
            // Only a complete opt-out is "unsubscribed". Tying this timestamp to the
            // first category removal would silently mute every other non-mandatory
            // category as well, because isSubscribedTo() reads a set timestamp as
            // "opted out of all of it".
            'unsubscribed_at' => $remaining === [] ? now() : null,
        ])->save();

        return response()->json([
            'message' => $remaining === []
                ? 'Unsubscribed from '.$delivery->category.' notifications.'
                : 'Unsubscribed from '.$delivery->category.'. Other notifications are unaffected.',
            'categories' => $remaining,
        ]);
    }
}
